my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('polls/', include('polls.urls', namespace='polls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
   path('', views.question_list, name='question_list'),
]


urlpatterns = [
   path('', views.question_list, name='question_list'),
   path('<int:question_id>/', views.question_detail, name='question_detail'),

]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question


def question_list(request):
    questions = Question.objects.all()
    return render(request, 'polls/question_list.html', {'questions': questions})


def question_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/question_detail.html', {'question': question})

polls/templates/polls/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}
    <link rel="stylesheet" href="{% static 'polls/styles.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}, <br>{{ question.pub_date }}, {{question.id}}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <table class="tabela"><tr><td>{{ choice.choice_text }}</td><td>votes={{ choice.votes }}</td><td>,id={{ choice.question.id}}</td></tr>
    <table/>
{% endfor %}
</ul>

</body>
</html>

polls/templates/polls/question_list.html
<!DOCTYPE html>
<html>
<head>{% load static %}
    <link rel="stylesheet" href="{% static 'polls/styles.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
   {% for question in questions %}
       <li><a href="{% url 'polls:question_detail' question.id %}">{{ question.question_text }}</a></li>

   {% endfor %}
</div>
</body>
</html>

polls/templates/polls/styles.html
body {
  background-color: lightblue;
}


h1 {
  color: navy;
  margin-left: 20px;
}